Deterministic `require`s in `test/runner`
We had (rack2) tests fail on 2.4 like this:

    /home/runner/work/puma/puma/lib/rack/handler/puma.rb:140:in `<top (required)>': undefined method `register' for Rack::Handler:Module (NoMethodError)
            from /home/runner/work/puma/puma/test/test_rack_handler.rb:6:in `require'
            from /home/runner/work/puma/puma/test/test_rack_handler.rb:6:in `<module:TestRackUp>'
            from /home/runner/work/puma/puma/test/test_rack_handler.rb:5:in `<top (required)>'
            from test/runner:32:in `require'
            from test/runner:32:in `block in <main>'
            from test/runner:32:in `each'
            from test/runner:32:in `<main>'