Fix the ability to focus individual tests (#3705)
* Fix `$ m test/test_log_writer.rb`

Before

```
TestLogWriter#test_parse_error:
NameError: uninitialized constant Puma::Server::UserFileDefaultOptions
    lib/puma/server.rb:80:in 'Puma::Server#initialize'
    test/test_log_writer.rb:128:in 'Class#new'
    test/test_log_writer.rb:128:in 'TestLogWriter#test_parse_error'

14 runs, 34 assertions, 0 failures, 1 errors, 0 skips
```

After:

```
$ be m test/test_log_writer.rb
/Users/rschneeman/.gem/ruby/3.4.5/gems/minitest-5.25.1/lib/minitest/mock.rb:33: warning: redefining 'object_id' may cause serious problems
Run options: -n "/^(test_parse_error|test_strings|test_debug_not_write_to_stdout_if_env_is_not_present|test_stdio|test_custom_log_formatter|test_null|test_log_writes_to_stdout|test_null_log_does_nothing|test_stdio_respects_sync|test_pid_formatter|test_error_writes_to_stderr_and_exits|test_debug_writes_to_stdout_if_env_is_present|test_write_writes_to_stdout|test_ssl_error)$/" --seed 44135

# Running:

..............

Fabulous run in 0.142536s, 98.2208 runs/s, 266.5993 assertions/s.

14 runs, 38 assertions, 0 failures, 0 errors, 0 skips
```

* Safer stop


I'm unsure what the exact conditions are that cause this, but it was hiding the "real" error (of a missing class). I think constants are loaded lazilly which happens before server is defined so calling stop on that variable is an error since it's a nil.

```
$ be m test/test_log_writer.rb
/Users/rschneeman/.gem/ruby/3.4.5/gems/minitest-5.25.1/lib/minitest/mock.rb:33: warning: redefining 'object_id' may cause serious problems
Run options: -n "/^(test_debug_writes_to_stdout_if_env_is_present|test_stdio|test_parse_error|test_debug_not_write_to_stdout_if_env_is_not_present|test_log_writes_to_stdout|test_error_writes_to_stderr_and_exits|test_strings|test_stdio_respects_sync|test_custom_log_formatter|test_write_writes_to_stdout|test_null_log_does_nothing|test_null|test_ssl_error|test_pid_formatter)$/" --seed 18564

# Running:

E.............

Fabulous run in 0.030120s, 464.8074 runs/s, 1128.8181 assertions/s.
Errors & Failures:

  1) Error:
TestLogWriter#test_parse_error:
NoMethodError: undefined method 'stop' for nil
    test/test_log_writer.rb:145:in 'TestLogWriter#test_parse_error'

14 runs, 34 assertions, 0 failures, 1 errors, 0 skips
```