Update minimum Ruby version to 3.0 (#3698)
* Update minimum Ruby to 3.0

* Remove Ruby 2.x based branching logic

* Update CI to Ruby 3.0+

* Update Rubocop target version

Updates the available performance cops, these needed fixing:

```
lib/puma/control_cli.rb:251:35: C: [Correctable] Performance/DeletePrefix: Use delete_prefix instead of sub.
          if Signal.list.key? sig.sub(/\ASIG/, '')
                                  ^^^
test/helper.rb:151:23: C: [Correctable] Performance/DeletePrefix: Use delete_prefix instead of sub.
    signal = sig.to_s.sub(/\ASIG/, '').to_sym
                      ^^^
test/runner:61:23: C: [Correctable] Performance/DeleteSuffix: Use delete_suffix instead of sub.
  file_arg = ARGV.pop.sub(/\.rb\z/, '')
                      ^^^
test/runner:63:68: C: [Correctable] Performance/DeleteSuffix: Use delete_suffix instead of sub.
    file_args = file_arg.split(File::PATH_SEPARATOR).map { |fn| fn.sub(/\.rb\z/, '') }
```

* ci: test.yml - fixup, remove rack1 job

* Update README

* Remove Random#bytes check

* Remove Process::Waiter check

* Remove append_cflags check

* String#split in Ruby 2.6+ takes a block

https://rubyapi.org/2.6/o/string#method-i-split

* Update comment to remove Ruby version

* Remove older jruby workaround

* Remove 2.5 reference and adjust code

The prior code used branching with an else and a negation. Flipping the order and removing the negation makes it easier to read.

Added code comments demonstrating why truffle ruby is special cased

* Remove Ruby 2 reference

* Update ruby image reference

https://hub.docker.com/layers/library/ruby/3.4.5-alpine/images/sha256-5dd7ab3c51da265f3b3a4eed3dfd90ffd116c32dc99d1a584c7141cca92a6c93

Trim trailing whitespace and make sure there's vertical whitespace after a paragraph, before a code section

* Remove Ruby version specific workaround

```
⛄️ 3.4.5 🚀 /Users/rschneeman/Documents/projects/puma (schneems/rev-min-ruby)
$ irb
irb(main):001> Thread.attr_accessor :puma_server
=> [:puma_server, :puma_server=]
```

* Remove Ruby 2.5 branch logic

* Remove Ruby <= 2.4 bugfix/workaround

Patch https://github.com/puma/puma/pull/1345 was added as a workaround for https://bugs.ruby-lang.org/issues/13632. 

The gem addition was already removed in another commit. An un-monkey-patched version of Ruby does not have this method, so the respond_to? check always returns false, so this code is currently a no-op anyway.

```
(irb):2:in '<main>': undefined method 'purge_interrupt_queue' for an instance of Thread (NoMethodError)
	from <internal:kernel>:168:in 'Kernel#loop'
	from /Users/rschneeman/.gem/ruby/3.4.5/gems/irb-1.15.2/exe/irb:9:in '<top (required)>'
	from /Users/rschneeman/.gem/ruby/3.4.5/bin/irb:25:in 'Kernel#load'
	from /Users/rschneeman/.gem/ruby/3.4.5/bin/irb:25:in '<main>'
```

* Remove rack 1 from Gemfile

This version was previously removed from CI, this is the only `rack1` reference in the codebase.

---------

Co-authored-by: MSP-Greg <Greg.mpls@gmail.com>