Getting a failure in the tests:
```
2.93s$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.2.gem (100%)
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```