Fix path could be nil in test_puma_server tests (#2981)
* Fix path could be nil in test_puma_server tests

When I run the test locally with
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
I got two failing tests[1] which complain path is nil.

Rearrange how we use tempfile (and use syswrite) in tests.
Extract into a tempfile_create method in test/helper.rb.

[1]

  1) Error:
TestPumaServer#test_file_body:
TypeError: no implicit conversion of nil into String
    test/test_puma_server.rb:158:in `exist?'
    test/test_puma_server.rb:158:in `ensure in test_file_body'
    test/test_puma_server.rb:158:in `test_file_body'
    /Users/hhh/dev/puma/test/helper.rb:89:in `block (4 levels) in run'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:117:in `timeout'
    /Users/hhh/dev/puma/test/helper.rb:87:in `block (3 levels) in run'

  2) Error:
TestPumaServer#test_file_to_path:
TypeError: no implicit conversion of nil into String
    test/test_puma_server.rb:177:in `exist?'
    test/test_puma_server.rb:177:in `ensure in test_file_to_path'
    test/test_puma_server.rb:177:in `test_file_to_path'
    /Users/hhh/dev/puma/test/helper.rb:89:in `block (4 levels) in run'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:117:in `timeout'
    /Users/hhh/dev/puma/test/helper.rb:87:in `block (3 levels) in run'

Co-Authored-By: MSP-Greg <MSP-Greg@users.noreply.github.com>

* Ensure we always close tempfile

seems like Windows will be happy if we do this

* Large body adjustments

Co-authored-by: MSP-Greg <MSP-Greg@users.noreply.github.com>
Co-authored-by: MSP-Greg <Greg.mpls@gmail.com>