Add missing securerandom require to test_puma_server
  1) Error:
TestPumaServer#test_file_to_path:
NameError: uninitialized constant TestPumaServer::SecureRandom

    random_bytes = SecureRandom.random_bytes(4096 * 32)
                   ^^^^^^^^^^^^
Did you mean?  SecurityError
    test/test_puma_server.rb:162:in `test_file_to_path'
    /Users/hhh/dev/puma/test/helper.rb:89:in `block (4 levels) in run'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:117:in `timeout'
    /Users/hhh/dev/puma/test/helper.rb:87:in `block (3 levels) in run'

  2) Error:
TestPumaServer#test_file_body:
NameError: uninitialized constant TestPumaServer::SecureRandom

    random_bytes = SecureRandom.random_bytes(4096 * 32)
                   ^^^^^^^^^^^^
Did you mean?  SecurityError
    test/test_puma_server.rb:147:in `test_file_body'
    /Users/hhh/dev/puma/test/helper.rb:89:in `block (4 levels) in run'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
    /Users/hhh/.rubies/ruby-3.1.0/lib/ruby/3.1.0/timeout.rb:117:in `timeout'
    /Users/hhh/dev/puma/test/helper.rb:87:in `block (3 levels) in run'

95 runs, 330 assertions, 0 failures, 2 errors, 0 skips